name: test

on:
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: |
          exit 0
          echo "::set-output name=status::success"
      - if: failure() && steps.test.outputs.status != 'success'
        run: echo failed
